version: '3.7'
services:
  pgsql:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: EXAMPLE_PASSWORD
    ports:
      - "5435:5432"
  app:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - pgsql

volumes:
  pgsql_data:
